export const staticPrimaryColor = '#5B8DEF'
export const staticPrimaryDarkenColor = '#4A7DD9'
export const themes = {
  light: {
    dark: false,
    colors: {
      'primary': staticPrimaryColor,
      'on-primary': '#fff',
      'primary-darken-1': '#4A7DD9',
      'secondary': '#8A8D93',
      'secondary-darken-1': '#7C7F84',
      'on-secondary': '#fff',
      'success': '#52C41A',
      'success-darken-1': '#49B017',
      'on-success': '#fff',
      'info': '#40A9FF',
      'info-darken-1': '#3998E6',
      'on-info': '#fff',
      'warning': '#FAAD14',
      'warning-darken-1': '#E09C12',
      'on-warning': '#fff',
      'error': '#FF4D4F',
      'error-darken-1': '#E64547',
      'on-error': '#fff',
      'background': '#F5F7FA',
      'on-background': '#4A4458',
      'surface': '#FFFFFF',
      'on-surface': '#4A4458',
      'grey-50': '#FAFAFA',
      'grey-100': '#F5F5F5',
      'grey-200': '#EEEEEE',
      'grey-300': '#E0E0E0',
      'grey-400': '#BDBDBD',
      'grey-500': '#9E9E9E',
      'grey-600': '#757575',
      'grey-700': '#616161',
      'grey-800': '#424242',
      'grey-900': '#212121',
      'perfect-scrollbar-thumb': '#dbdade',
      'skin-bordered-background': '#fff',
      'skin-bordered-surface': '#fff',
      'expansion-panel-text-custom-bg': '#fafafa',
      'track-bg': '#F0F2F8',
      'chat-bg': '#F7F6FA',
    },
    variables: {
      'code-color': '#d400ff',
      'overlay-scrim-background': '#4A4458',
      'tooltip-background': '#1A0E33',
      'overlay-scrim-opacity': 0.5,
      'hover-opacity': 0.04,
      'focus-opacity': 0.1,
      'selected-opacity': 0.08,
      'activated-opacity': 0.16,
      'pressed-opacity': 0.14,
      'dragged-opacity': 0.1,
      'disabled-opacity': 0.4,
      'border-color': '#4A4458',
      'border-opacity': 0.12,
      'table-header-color': '#F6F7FB',
      'high-emphasis-opacity': 0.85,
      'medium-emphasis-opacity': 0.6,

      // 👉 shadows - 更柔和的阴影
      'shadow-key-umbra-color': '#4A4458',
      'shadow-xs-opacity': '0.08',
      'shadow-sm-opacity': '0.10',
      'shadow-md-opacity': '0.12',
      'shadow-lg-opacity': '0.14',
      'shadow-xl-opacity': '0.16',
    },
  },
  dark: {
    dark: true,
    colors: {
      'primary': '#5B8DEF',
      'on-primary': '#fff',
      'primary-darken-1': '#4A7DD9',
      'secondary': '#8A8D93',
      'secondary-darken-1': '#7C7F84',
      'on-secondary': '#fff',
      'success': '#52C41A',
      'success-darken-1': '#49B017',
      'on-success': '#fff',
      'info': '#40A9FF',
      'info-darken-1': '#3998E6',
      'on-info': '#fff',
      'warning': '#FAAD14',
      'warning-darken-1': '#E09C12',
      'on-warning': '#fff',
      'error': '#FF4D4F',
      'error-darken-1': '#E64547',
      'on-error': '#fff',
      'background': '#131a24',
      'on-background': '#c9d1d9',
      'surface': '#1a2332',
      'on-surface': '#c9d1d9',
      'grey-50': '#1f2b3a',
      'grey-100': '#243040',
      'grey-200': '#2f3d4f',
      'grey-300': '#3d4d60',
      'grey-400': '#526275',
      'grey-500': '#6e7f90',
      'grey-600': '#8b949e',
      'grey-700': '#a8b1ba',
      'grey-800': '#c9d1d9',
      'grey-900': '#e6edf3',
      'perfect-scrollbar-thumb': '#2f3d4f',
      'skin-bordered-background': '#1a2332',
      'skin-bordered-surface': '#1a2332',
      'expansion-panel-text-custom-bg': '#1f2b3a',
      'track-bg': '#1f2b3a',
      'chat-bg': '#1a2332',
    },
    variables: {
      'code-color': '#d400ff',
      'overlay-scrim-background': '#131a24',
      'tooltip-background': '#F7F4FF',
      'overlay-scrim-opacity': 0.6,
      'hover-opacity': 0.06,
      'focus-opacity': 0.12,
      'selected-opacity': 0.08,
      'activated-opacity': 0.16,
      'pressed-opacity': 0.14,
      'disabled-opacity': 0.4,
      'dragged-opacity': 0.1,
      'border-color': '#c9d1d9',
      'border-opacity': 0.08,
      'table-header-color': '#1c2333',
      'high-emphasis-opacity': 0.95,
      'medium-emphasis-opacity': 0.6,

      // 阴影
      'shadow-key-umbra-color': '#000000',
      'shadow-xs-opacity': '0.20',
      'shadow-sm-opacity': '0.24',
      'shadow-md-opacity': '0.28',
      'shadow-lg-opacity': '0.32',
      'shadow-xl-opacity': '0.36',
    },
  },
}
export default themes
